PUT http://localhost:5218/api/courses/39b8c3fb-6481-4169-a4e8-ebd9c1185024
Content-Type: application/json

{
  "name": "Sistemas Operacionais",
  "description": "Curso básico de sistemas operacionais que engloba conceitos como o gerenciamento processos e de memória, sistemas de arquivos e segurança."
}