PUT http://localhost:5218/api/members/0dfecf52-4270-41d6-b1b3-96ff7db71c7b
Content-Type: application/json
Accept: application/json

{
  "firstName": "João",
  "lastName": "Paulo Back",
  "documentNumber": "11154328937"
}