POST http://localhost:5218/api/subscriptions
Content-Type: application/json

{
  "idPlan": "15455BCC-36FD-4256-AF59-0C3BA6BAB3BA",
  "idMember": "a9debca2-17a2-4679-9359-3e57e9cd157f",
  "value": 100.00
}